### ISSUE TITLE
Please help me to create Dynamic Menu 

### ISSUE THREAD

**Issue by infocodeart** [cyberzilla/dycms#4]
I am using Codeigniter Frame work, it is working fine, only problem how to Create Dynamic Menu. app.json having menu data but my project required dynamic menu, Menu information is stored database. 

Please help me solve this problem.

Infocodeart

**Comment by cyberzilla** [comment]
According to app.json, the menu is divided into two, parent menu and child menu, if your parent & child menu is merge in db table, just "select * from menu", but if different table you must join before encode into json
